device: cuda:0

run_train:
  epoch: 3
  grad_enabled: False

dataset:
  S:
    base: /mlflow/data/dataset
    query:
      - is_anomaly_image == 1 &
        crop_type == 'tobu' &
        supervised == 'train'
  C:
    base: /mlflow/data/dataset
    query:
      - is_anomaly_image == 1 &
        crop_type == 'tobu' &
        supervised == 'train'
      - is_anomaly_product == 0 &
        crop_type == 'tobu' &
        supervised == 'train'
  test:
    base: /mlflow/data/dataset
    query:
      - crop_type == 'tobu' &
        supervise == 'test'

dataloader:
  S:
    batch_size: 32
    shuffle: True
  C:
    batch_size: 32
    shuffle: True
  test:
    batch_size: 1
    shuffle: True

model:
  S:
    name: DeepLabV3
    pth:
    args:
      pretrained: True
      num_classes: 2
  C:
    name: VGG19
    pth:
    args:
      pretrained: True
      in_channels: 2
      out_features: 2

augs:
  height: 64
  width: 64
  S:
    yaml: /mlflow/code/ssad/conf/augs/train_semseg.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}
  C:
    yaml: /mlflow/code/ssad/conf/augs/train_classifier.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}
  test:
    yaml: /mlflow/code/ssad/conf/augs/test.yaml
    args:
      Resize:
        height: ${augs.height}
        width: ${augs.width}

optimizer:
  S:
    name: Adam
    args:
      lr: 0.0002
      weight_decay: 0.00001
  C:
    name: Adam
    args:
      lr: 0.0002
      weight_decay: 0.00001

criterion:
  S:
    name: CrossEntropy2D
    args:
      reduction: mean
  C:
    name: CrossEntropyLoss
    args:
