__version__: 0.4.6
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.5
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
      always_apply: false
      p: 1
    - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip
      always_apply: false
      p: 1
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.75
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.CLAHE
      always_apply: false
      clip_limit:
      - 1
      - 4.0
      p: 1
      tile_grid_size:
      - 8
      - 8
    - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
      always_apply: false
      eps: null
      gamma_limit:
      - 80
      - 120
      p: 1
    - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
      - -0.2
      - 0.2
      contrast_limit:
      - -0.2
      - 0.2
      p: 1
  - __class_fullname__: albumentations.augmentations.transforms.Resize
    always_apply: false
    height: 256
    interpolation: 1
    p: 1
    width: 256
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    always_apply: false
    max_pixel_value: 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    p: 1
    std:
    - 0.229
    - 0.224
    - 0.225
  - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
    always_apply: false
    p: 1
